name: uni-q ci-cd

on:
  push:
    branches:
      - main
    paths:
      - 'packages/common/qslint/**'
      - '.github/workflows/uni-q-publish.yml'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          
      - name: Install dependencies
        run: npm install
        
      - name: Build
        run: npm run build
        
      - name: Test
        run: npm run test
        
      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd packages/common/qslint
          npm publish --access public
